name: "SolarLife BLE MPPT"
version: "1.0.0"
slug: "solarlife"
description: "Reads SolarLife MPPT over BLE and sends data to MQTT"
startup: services
boot: auto
init: false
host_network: true
privileged: true
full_access: true
arch:
  - aarch64
options:
  device_mac: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  interval: 30
schema:
  device_mac: str
  mqtt_host: str
  mqtt_port: int
  interval: int
devices:
  - /dev/hci0
